### ISSUE TITLE
governance-os can’t be connected to Substrate Front End Template

### ISSUE THREAD

**Issue by kenokenobingo** [NucleiStudio/governance-os#39]
When running governance-os on my local computer, the [front end template](https://substrate.dev/substrate-front-end-template/) can’t connect to it (regardless of using it locally or on substrate.dev). The front end template is able to connect to `canvas` or the basic `substrate-node-template`, though.

**Comment by ETeissonniere** [comment]
Have you tried using the [Polka JS UI](https://polkadot.js.org/apps), you will need to use the [custom types](https://github.com/NucleiStudio/governance-os/blob/master/types.json) though.

Also please note that the node does not use the normal `balance` template though. I had to make a custom way to support multiple assets.

You can find some nice tutorials (also they may have changed a bit) in the [folder dedicated to the web 3 foundation](https://github.com/NucleiStudio/governance-os/tree/master/.w3f) too.

**Comment by kenokenobingo** [comment]
Yes, using the Polka JS UI works out. I just thought there might be a bug because of the problems with the front end template.
